'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Mind_Mania.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _178007() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("178007", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _1780071() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("1780071", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _95131645d89bf13e54bfbe4f78365804() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("95131645d89bf13e54bfbe4f78365804", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property abstract_rainbow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("abstract-rainbow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property animated_gifs_of_fighting_game_backgrounds_25() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("animated-gifs-of-fighting-game-backgrounds-25", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property ARROW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("ARROW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BACKGROUND() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BACKGROUND", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property BACKGROUNDROCK() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("BACKGROUNDROCK", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property blueborder() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("blueborder", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat6() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat6", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat8() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat8", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boat9() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boat9", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boRQGDz() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boRQGDz", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property boulder_clipart_13308187491768495795Boulders_svg_hi() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("boulder-clipart-13308187491768495795Boulders.svg.hi", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CASUAL() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CASUAL", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property character() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("character", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CHEST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CHEST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property chest_clipart_treasure_chest5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("chest-clipart-treasure-chest5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property CLOSED_CHEST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("CLOSED-CHEST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COMPASS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COMPASS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COMPASS1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COMPASS1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COMPASS2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COMPASS2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d21e5966_golfgreen() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d21e5966_golfgreen", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property d37443d62d4962425348079bc051aece() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("d37443d62d4962425348079bc051aece", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property digimadmedia_stock_vectors_1364067057_abstract_red_purple_background() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("digimadmedia-stock-vectors-1364067057-abstract-red-purple-background", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property DOWN() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DOWN", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property fbfbffvfvf() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("fbfbffvfvf", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finder_clipart_41_clip_art_bird_blue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finder-clipart-41-clip_art_bird_blue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finder_clipart_41_clip_art_bird_blue1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finder-clipart-41-clip_art_bird_blue1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finder_clipart_41_clip_art_bird_blue2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finder-clipart-41-clip_art_bird_blue2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property finder_clipart_41_clip_art_bird_blue3() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("finder-clipart-41-clip_art_bird_blue3", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property footer() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("footer", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property footer1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("footer1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Game() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Game", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property grass1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("grass1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HALF_CHEST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HALF-CHEST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property html_color_codes_color_tutorials_hero_00e10b1f() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("html-color-codes-color-tutorials-hero-00e10b1f", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property html_color_codes_color_tutorials_hero_00e10b1f1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("html-color-codes-color-tutorials-hero-00e10b1f1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property INVENTORY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("INVENTORY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property LEFT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("LEFT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property media_play_symbol_318_47368() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("media-play-symbol_318-47368", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MJMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MJMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mountain_and_forest_powerpoint_backgrounds_travel_discover_the_vw0oTd_clipart2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mountain-and-forest-powerpoint-backgrounds-travel-discover-the-vw0oTd-clipart2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property MOUNTAIN_DIVE_CHAR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("MOUNTAIN DIVE CHAR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property mygeomatic_Rapporteur_5_2400px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mygeomatic-Rapporteur-5-2400px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OPEN_CHEST() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OPEN-CHEST", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pause_logo_large() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pause_logo_large", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property plane_pulling_banner_vector_8550070() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("plane-pulling-banner-vector-8550070", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PROFILE() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PROFILE", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pshkvsky_gif2code_10_js() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pshkvsky_gif2code_10_js", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property qmtumvxj5yow() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("qmtumvxj5yow", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property question_mark_318_52837() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("question-mark_318-52837", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property return_clipart_go_back_icon_md_14FB4BD5B0E65A3E735() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("return-clipart-go-back-icon-md-14FB4BD5B0E65A3E735", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RIGHT() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RIGHT", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property rock_clipart_clipart_harvestable_resources_rock() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("rock-clipart-clipart-harvestable-resources-rock", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property RTMG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("RTMG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scale_1_10() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scale-1-10", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property scale_1_10vertical() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("scale-1-10vertical", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tent_clip_art_green_tent_clip_art_vector_clip_art_online_royalty_free_public_600x284() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tent-clip-art-green-tent-clip-art-vector-clip-art-online-royalty-free-public-600x"& _ 
                        "284", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tree_trunk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tree-trunk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tree_trunkflipped() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tree-trunkflipped", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tropical_island_clipart_island_clipart_island_Clip_Art() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tropical-island-clipart-island-clipart-island_Clip_Art", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property tumblr_nlkzd1pEkS1qi83i1o1_400() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("tumblr_nlkzd1pEkS1qi83i1o1_400", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Untitled_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Untitled-1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property UP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("UP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property wind_clip_art_for_teachers_clipart_panda_free_clipart_images_wSd7qo_clipart() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wind-clip-art-for-teachers-clipart-panda-free-clipart-images-wSd7qo-clipart", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
